if( CMAKE_TOOLCHAIN_FILE )

set (CMAKE_SYSTEM_NAME Windows)
set (TOOLCHAIN_PREFIX i686-pc-mingw32-)
set (TARGET_ARCH i686-pc-mingw32)

#set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
find_program(CMAKE_C_COMPILER NAMES ${TOOLCHAIN_PREFIX}gcc)
#set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++-4.8.4)
find_program(CMAKE_CXX_COMPILER NAMES ${TOOLCHAIN_PREFIX}g++-4.8.4)
#set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}windres)
find_program(CMAKE_RC_COMPILER NAMES ${TOOLCHAIN_PREFIX}windres)
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})
get_filename_component(TOOLCHAIN_FILE ${CMAKE_TOOLCHAIN_FILE} NAME)
set(TOOLCHAIN_CONF ${CMAKE_SOURCE_DIR}/cmake/Modules/${TOOLCHAIN_FILE})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

endif()
